### PR TITLE
Add the option to edit the book

### PR DESCRIPTION
**Pull request by llrs**

### CODE REVIEW

**Comment by oscarbaruffa** [comment]
thanks!

**Comment by oscarbaruffa** [comment]
Seems the edit option is showing. I've had this issue on another book as well, not sure why it never shows.

**Comment by llrs** [comment]
How do you build it? Do you each time do it locally? If so, the problem might be on the options used.

**Comment by oscarbaruffa** [comment]
Ok first problem is I forgot to Push changes so now your contribution shows  :). Still no edit though.

Yes I build locally (couldn't get that auto build to work, some sort of local package issues on Windows). 

Should I look at YAML options or local build options? 

Thanks for your help!

**Pull request merged**
