### PR TITLE
Update 020-book_list.Rmd

### PR DESCRIPTION
**Pull request by mca91**
Added *Introduction to Econometrics with R*.

### CODE REVIEW

**Comment by oscarbaruffa** [comment]
Thanks, its already there though :) https://www.bigbookofr.com/field-specific.html#introduction-to-econometrics-with-r

I know not easy with the books not being properly alphabetised but I have a plan for how to fix that one day

**Comment by mca91** [comment]
Thanks and sorry for coming back to this so late, but could you please update the description text? I feel that the one in my PR is more suitable:

Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. *Introduction to Econometrics with R* is an interactive companion to the well-received textbook *Introduction to Econometrics* by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programming and guides students in implementing the empirical applications presented throughout the textbook using the newly acquired skills. This is supported by interactive programming exercises and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js.

**Comment by oscarbaruffa** [comment]
No problem, I've updated it https://www.bigbookofr.com/field-specific.html#introduction-to-econometrics-with-r

**Comment by mca91** [comment]
Great, thanks again!

**Pull request closed without merging**
