### PR TITLE
Added Cryptocurrency Research: Open Source R Tutorial

### PR DESCRIPTION
**Pull request by gbganalyst**
Dear Oscar,

The tutorial titled Cryptocurrency Research: Open Source R Tutorial fits the following section of Big Book of R:

- Data Science
- Data Visualization
- Getting, cleaning and wrangling data
- Machine Learning
- R programming 
- Time Series Analysis and Forecasting

I have added it to them accordingly.

Please check the tutorial via <https://cryptocurrencyresearch.org> to see it yourself.

### CODE REVIEW

**Comment by oscarbaruffa** [comment]
Oooh thanks! Looks interesting 🙂.

I think it's under way too many categories to though. Technically
everything could fit under most of those.

I suggest rather putting under "Field specific" because it is focused on a
very specific field but there's not enough crypto books to warrant a
seperate section.

If you're willing to move it that would be great, but I can also do it and
still credit you for the add.

Thanks again!

**Comment by gbganalyst** [comment]
Ok, let me add it to section 25: Field specific.

**Comment by gbganalyst** [comment]
I have added it to the field specific section. Please check it out. In addition, I have corrected some spelling errors in the Big Book of R.

**Review by oscarbaruffa — APPROVED** [review]
thanks for fixing some typos too

**Comment by gbganalyst** [comment]
You are welcome Oscar and thank you for the leadership.

**Pull request merged**
